# Generated by Django 4.2.7 on 2024-01-08 21:53

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('DNI', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicoResidente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('DNI', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('matricula', models.CharField(max_length=6, unique=True)),
                ('nacionalidad', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicoStaff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('DNI', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('matricula', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('DNI', models.CharField(default='00.000.000', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message="El DNI debe tener el formato: 'xx.xxx.xxx'", regex='^\\d{2}\\.\\d{3}\\.\\d{3}$')])),
                ('matricula', models.CharField(default='000.000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="La matrícula debe tener el formato: 'xxx.xxx'", regex='^\\d{3}\\.\\d{3}$')])),
                ('email', models.EmailField(default='Desconocido', max_length=200)),
                ('nacionalidad', models.CharField(default='Desconocida', max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('repetido', models.BooleanField(default=False)),
                ('grupo', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('referente', models.CharField(max_length=200)),
            ],
        ),
    ]
