# Generated by Django 4.2.7 on 2023-12-27 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('DNI', models.CharField(default='00.000.000', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message="El DNI debe tener el formato: 'xx.xxx.xxx'", regex='^\\d{2}\\.\\d{3}\\.\\d{3}$')])),
                ('matricula', models.CharField(default='000.000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="La matrícula debe tener el formato: 'xxx.xxx'", regex='^\\d{3}\\.\\d{3}$')])),
                ('email', models.EmailField(default='Desconocido', max_length=200)),
                ('nacionalidad', models.CharField(default='Desconocida', max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('repetido', models.BooleanField(default=False)),
                ('grupo', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('referente', models.CharField(max_length=200)),
            ],
        ),
    ]
