# Generated by Django 4.2.7 on 2024-01-20 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('fecha_ingreso_residencia', models.DateField(verbose_name='Fecha de Ingreso')),
                ('pais_nacionalidad', models.CharField(max_length=50, verbose_name='País de Nacionalidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
