# Generated by Django 4.2.7 on 2024-01-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('apellido_paciente', models.CharField(max_length=255)),
                ('dni_paciente', models.CharField(max_length=10, unique=True)),
                ('fecha_estudio', models.DateField()),
                ('cuerpo_preinforme', models.TextField()),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinformes', to='residentesdm.medicoresidente')),
            ],
        ),
    ]
