# Generated by Django 4.2.7 on 2023-12-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('repetido', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
