# Generated by Django 4.2.7 on 2023-12-28 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0002_medicoresidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoresidente',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
