# Generated by Django 4.2.7 on 2023-12-03 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0002_residente_alter_sede_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='dni',
        ),
        migrations.AddField(
            model_name='residente',
            name='matricula',
            field=models.CharField(default='000.000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="La matrícula debe tener el formato: 'xx.xxx.xxx'", regex='^\\d{2}\\.\\d{3}\\.\\d{3}$')]),
        ),
        migrations.AddField(
            model_name='residente',
            name='nacionalidad',
            field=models.CharField(default='Desconocida', max_length=200),
        ),
        migrations.AddField(
            model_name='residente',
            name='DNI',
            field=models.CharField(default='00.000.000', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message="El DNI debe tener el formato: 'xx.xxx.xxx'", regex='^\\d{2}\\.\\d{3}\\.\\d{3}$')]),
        ),
    ]
