# Generated by Django 4.2.7 on 2024-01-23 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0004_alter_residente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusuario',
            name='es_administrativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residente',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='DNI'),
        ),
        migrations.CreateModel(
            name='CuerpoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
