# Generated by Django 4.2.7 on 2024-01-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0005_cuerpoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicostaff',
            name='matricula',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
