# Generated by Django 4.2.7 on 2023-12-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0006_evaluacion_evaluado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
