# Generated by Django 4.2.7 on 2024-01-03 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residentesdm', '0006_medicostaff_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinformes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
