# Generated by Django 4.2.7 on 2023-12-04 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0007_delete_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluacion_residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectopositivo', models.TextField()),
                ('aspectonegativo', models.TextField()),
                ('nota', models.IntegerField(default=0)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentesdm.residente')),
            ],
        ),
    ]
