# Generated by Django 4.2.7 on 2023-12-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0008_evaluacion_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectos_positivos', models.TextField()),
                ('aspectos_negativos', models.TextField()),
                ('nota', models.IntegerField()),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentesdm.residente')),
            ],
        ),
        migrations.DeleteModel(
            name='evaluacion_residente',
        ),
    ]
