# Generated by Django 4.2.7 on 2023-12-04 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0009_evaluacion_delete_evaluacion_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
