# Generated by Django 4.2.7 on 2023-12-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0010_evaluacion_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
