# Generated by Django 4.2.7 on 2023-12-05 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0011_delete_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectos_positivos', models.TextField()),
                ('aspectos_negativos', models.TextField()),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentesdm.residente')),
            ],
        ),
    ]
