# Generated by Django 4.2.7 on 2023-12-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0012_evaluacionresidente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluacionResidente',
            new_name='Evaluacion',
        ),
    ]
