# Generated by Django 4.2.7 on 2023-12-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0013_rename_evaluacionresidente_evaluacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
