# Generated by Django 4.2.7 on 2023-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0015_evaluacion_residentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='grupo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
