# Generated by Django 4.2.7 on 2023-12-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentesdm', '0016_residente_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evaluacion_residentes',
        ),
    ]
